version: 2.1

jobs:
  build:
    macos:
      xcode: 13.3.0
    steps:
      - checkout
      - run:
          name: "Build"
          command: swift build
  test:
    macos:
      xcode: 13.3.0
    steps:
      - checkout
      - run:
          name: "Test"
          command: swift test

workflows:
  main:
    jobs:
      - build
      - test
