name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: List Xcode Versions
      run: ls /Applications | grep Xcode
    - name: Set Xcode Version
      run: sudo xcode-select -s /Applications/Xcode_13.3.app
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
